### ISSUE TITLE
Windows 32 bit support

### ISSUE THREAD

**Issue by finder0009** [ImpulseAdventure/GUIslice-Builder-source#31]
win7 32bit installer

**Comment by ImpulseAdventure** [comment]
Hi @finder0009 -- it looks like this might be a duplicate issue of #20 that you filed on Feb 6?

From that discussion, I understand that you were able to successfully run the Builder on Windows 7 32-bit. From the summary of steps, we had:
- Install **Java 1.8 JRE 32-bit**
- Download the **`builder-linux-#.#.#.tar.gz`** from the latest release notes. eg. [builder-linux-0.13.0.3.tar.gz](https://github.com/ImpulseAdventure/GUIslice-Builder-source/releases/download/v0.13.0.3/builder-linux-0.13.0.3.tar.gz) (note we are using the `.jar` file from the LINUX release)
- Follow the install steps shown in https://github.com/ImpulseAdventure/GUIslice-Builder-source/issues/20#issuecomment-461444816

Please let us know if that enables you to run the Builder in Windows 7 32-bit mode.
Thanks!

**Comment by Pconti31** [comment]
Hi, It should be noted that the 64-bit has been removed from the install builder-win-0.13.0.3.exe
because it is in fact a 32-bit installer.  Now we do build using a 64-bit Java JRE and recommend
it for its extra memory space but a 32-bit JRE should also work if not as well.

So the question is what isn't running?  
What version of GUIsliceBuilder did you use? The latest is 0.13.0.3
Where did you install GUIsliceBuilder?
Are the files present in this installation folder?
If so, open a ms/dos cmd box.
cd to the install folder for example:
`cd "C:\Program Files (x86)\GUIsliceBuilder"`
once in the folder type in:
`echo %JAVA_HOME%`
Does this show the path to your 32-bit Java JRE?
if not you need to add JAVA_HOME to your environment variables by going to
Control Panel->System->Advanced System Settings->Environment Variables
If the path seems right enter:
`%JAVA_HOME%\bin\java -version`
this should output:
java version "1.8.0_192"
if that works enter:
Note that the name of the jar must match your installed version here I assume it's 0.13.0.3.
`%JAVA_HOME%\bin\java -classpath .\lib\builder-0.13.0.3.jar builder.Builder'
Did any error messages show up?

Paul--

**Comment by Pconti31** [comment]
One more thing. If the installer doesn't run at all then it could be windows 7 security problem.
Right click on the  builder-win-0.13.0.3.exe to examine its properties.
if you see something like:
Security: This file came from another computer and might be blocked to protect this computer.

Then check the UnBlock box to allow you to run the installer.
Paul--

**Comment by finder0009** [comment]
Thank you every thing was done the old way

‫في الأربعاء، 11 سبتمبر 2019 في 8:37 ص تمت كتابة ما يلي بواسطة ‪Calvin
Hass‬‏ <‪notifications@github.com‬‏>:‬

**Comment by finder0009** [comment]
Thank you every thing went fine just the way you have mentioned

‫في السبت، 14 سبتمبر 2019 في 12:32 ص تمت كتابة ما يلي بواسطة ‪Alaa
Tuffaha‬‏ <‪finder0009@gmail.com‬‏>:‬

**Comment by finder0009** [comment]
I just modified the path in the The GUIslice.bat:

set JAVA_EXE="%JAVA_HOME%/bin/javaw.exe"

to become  like this

set JAVA_EXE="%JAVA_HOME%/javaw.exe"

The  win installer worked and the builder also worked

It also worker the other way using linux installer using the same
modification in
The GUIslice.bat :

@echo off
set CLASSPATH=.;%JAVA_HOME%\lib
start "" /min "%JAVA_HOME%\bin\javaw" -jar builder-0.10.4-beta7.jar

Thank you for your instructions


‫في الأربعاء، 11 سبتمبر 2019 في 4:50 م تمت كتابة ما يلي بواسطة ‪Paul
Conti‬‏ <‪notifications@github.com‬‏>:‬

**Comment by finder0009** [comment]
I just modified the path in the The GUIslice.bat:

set JAVA_EXE="%JAVA_HOME%/bin/javaw.exe"

to become  like this

set JAVA_EXE="%JAVA_HOME%/javaw.exe"

The  win installer worked and the builder also worked

It also worker the other way using linux installer using the same
modification in
The GUIslice.bat :

@echo off
set CLASSPATH=.;%JAVA_HOME%\lib
start "" /min "%JAVA_HOME%\bin\javaw" -jar builder-0.10.4-beta7.jar

Thank you for your instructions

‫في السبت، 14 سبتمبر 2019 في 12:35 ص تمت كتابة ما يلي بواسطة ‪Alaa
Tuffaha‬‏ <‪finder0009@gmail.com‬‏>:‬

**Comment by Pconti31** [comment]
Happy to help.
Paul--
